name: "Build and push"

on:
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.23
          cache: false
      - uses: actions/checkout@v4
      - name: go-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 5m0s
